// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URF.Core.Sample.v3.EF.Contexts;

namespace URF.Core.Sample.v3.EF.Migrations
{
    [DbContext(typeof(UrfSampleContext))]
    [Migration("20201124221503_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("URF.Core.Sample.v3.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductName = "Chai",
                            UnitPrice = 1m
                        },
                        new
                        {
                            Id = 2,
                            ProductName = "Chang",
                            UnitPrice = 2m
                        },
                        new
                        {
                            Id = 3,
                            ProductName = "Cappuccino",
                            UnitPrice = 3m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
